In [36]:
import pandas as pd

In [37]:
df = pd.read_csv("train_data.csv")
df

,event_id,time_to_tca,mission_id,risk,max_risk_estimate,max_risk_scaling,miss_distance,relative_speed,relative_position_r,relative_position_t,...,t_sigma_rdot,c_sigma_rdot,t_sigma_tdot,c_sigma_tdot,t_sigma_ndot,c_sigma_ndot,F10,F3M,SSN,AP
0,0,1.566798,5,-10.204955,-7.834756,8.602101,14923.0,13792.0,453.8,5976.6,...,0.147350,58.272095,0.004092,0.165044,0.002987,0.386462,89.0,83.0,42.0,11.0
1,0,1.207494,5,-10.355758,-7.848937,8.956374,14544.0,13792.0,474.3,5821.2,...,0.059672,57.966413,0.003753,0.164383,0.002933,0.386393,89.0,83.0,42.0,11.0
2,0,0.952193,5,-10.345631,-7.847406,8.932195,14475.0,13792.0,474.6,5796.2,...,0.039258,57.907599,0.003576,0.164352,0.002967,0.386381,89.0,83.0,42.0,11.0
3,0,0.579669,5,-10.337809,-7.845880,8.913444,14579.0,13792.0,472.7,5838.9,...,0.022066,57.993905,0.003298,0.164309,0.002918,0.386400,89.0,83.0,40.0,14.0
4,0,0.257806,5,-10.391260,-7.852942,9.036838,14510.0,13792.0,478.7,5811.1,...,0.015075,57.946717,0.003670,0.164172,0.003220,0.386388,89.0,83.0,40.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162629,13153,3.029751,1,-7.108630,-5.142668,7.561579,2307.0,14976.0,-472.1,-159.9,...,0.071060,48.480202,0.011479,0.145746,0.002764,0.231577,81.0,84.0,48.0,18.0
162630,13153,2.799253,1,-7.070070,-5.137869,7.471857,2254.0,14976.0,-469.7,-163.3,...,0.063959,48.565132,0.009935,0.145729,0.002678,0.231583,78.0,84.0,49.0,19.0
162631,13153,2.385399,1,-7.066209,-5.137034,7.463470,2259.0,14976.0,-469.3,-158.8,...,0.059657,48.547317,0.009491,0.145745,0.002632,0.231582,78.0,84.0,49.0,19.0
162632,13153,2.043339,1,-7.028307,-5.131297,7.378397,2257.0,14976.0,-465.2,-160.3,...,0.039351,48.540602,0.002612,0.145734,0.002631,0.231583,78.0,84.0,49.0,19.0
162633,13153,1.618095,1,-7.172372,-5.152181,7.705750,2185.0,14976.0,-479.6,-156.0,...,0.047452,48.673155,0.009494,0.145716,0.002693,0.231592,78.0,84.0,48.0,10.0

Data points with time_to_tca within 2 days are removed from the dataset due to the constraint of the challenge to use only CDMs atleast 2 days prior to tca:

In [39]:
challenge_df = df[df['time_to_tca'] >= 2].reset_index(drop=True)
challenge_df

,event_id,time_to_tca,mission_id,risk,max_risk_estimate,max_risk_scaling,miss_distance,relative_speed,relative_position_r,relative_position_t,...,t_sigma_rdot,c_sigma_rdot,t_sigma_tdot,c_sigma_tdot,t_sigma_ndot,c_sigma_ndot,F10,F3M,SSN,AP
0,1,6.530455,5,-7.561299,-7.254301,2.746782,2392.0,3434.0,74.3,2317.1,...,0.278354,84.677411,0.006980,0.320622,0.004199,0.047385,71.0,88.0,0.0,2.0
1,1,5.561646,5,-9.315693,-7.468904,7.223137,3587.0,3434.0,99.0,3475.4,...,0.240907,63.860857,0.006402,0.264636,0.003725,0.040020,70.0,87.0,13.0,14.0
2,1,5.226504,5,-7.422508,-7.051001,2.956639,7882.0,3434.0,-50.0,-7638.3,...,0.240198,56.764910,0.005906,0.259109,0.003588,0.083247,70.0,87.0,13.0,14.0
3,1,3.570013,5,-9.248105,-7.327533,7.425994,26899.0,3434.0,-82.0,-26067.0,...,0.124802,30.242768,0.005883,0.174956,0.003408,0.058311,71.0,87.0,21.0,5.0
4,2,6.983474,2,-10.816161,-6.601713,13.293159,22902.0,14348.0,-1157.6,-6306.2,...,0.153332,39.695541,0.009370,0.269965,0.003886,0.339406,73.0,77.0,27.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111934,13153,3.408859,1,-7.080451,-5.140501,7.492353,2205.0,14976.0,-472.5,-159.4,...,0.075627,48.666693,0.012352,0.145778,0.002878,0.231589,81.0,84.0,48.0,18.0
111935,13153,3.029751,1,-7.108630,-5.142668,7.561579,2307.0,14976.0,-472.1,-159.9,...,0.071060,48.480202,0.011479,0.145746,0.002764,0.231577,81.0,84.0,48.0,18.0
111936,13153,2.799253,1,-7.070070,-5.137869,7.471857,2254.0,14976.0,-469.7,-163.3,...,0.063959,48.565132,0.009935,0.145729,0.002678,0.231583,78.0,84.0,49.0,19.0
111937,13153,2.385399,1,-7.066209,-5.137034,7.463470,2259.0,14976.0,-469.3,-158.8,...,0.059657,48.547317,0.009491,0.145745,0.002632,0.231582,78.0,84.0,49.0,19.0
111938,13153,2.043339,1,-7.028307,-5.131297,7.378397,2257.0,14976.0,-465.2,-160.3,...,0.039351,48.540602,0.002612,0.145734,0.002631,0.231583,78.0,84.0,49.0,19.0

Analysing missing values in the dataset:

In [40]:
null_percentage = challenge_df.isnull().mean()*100
print('total rows with values in all variables: ', challenge_df.dropna().shape[0])
print('total rows in the data: ', challenge_df.shape[0])
print('percentage of data with missing values: ', (1 - challenge_df.dropna().shape[0]/ challenge_df.shape[0]))
print('Top 10 Highest percentage of missing values and corresponding columns:')
null_percentage.sort_values(ascending=False)[:10]

total rows with values in all variables:  66736
total rows in the data:  111939
percentage of data with missing values:  0.40381815095721774
Top 10 Highest percentage of missing values and corresponding columns:

c_rcs_estimate    32.819661
c_cndot_tdot       5.481557
c_crdot_r          5.481557
c_crdot_t          5.481557
c_crdot_n          5.481557
c_ctdot_t          5.481557
c_ctdot_n          5.481557
c_ctdot_rdot       5.481557
c_cndot_r          5.481557
c_cndot_t          5.481557
dtype: float64

The key steps used to remove missing values are:

1. Grouping the data by the mission_id column

2. Using ffill() and bfill() to fill the missing values with the nearest non-missing value in the same mission_id

In [41]:
#Replace missing values with nearest neighbour

imputed_df = (
    challenge_df.groupby('mission_id')
    .apply(lambda x: x.ffill().bfill())
    .reset_index(drop=True)
)
print(challenge_df.isna().sum().sum())
print(imputed_df.isna().sum().sum())

C:\Users\Atharva\AppData\Local\Temp\ipykernel_6124\1060367806.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.ffill().bfill())

242435
0

Handling Outliers:

In [42]:
def detect_outliers(imputed_df):
    outlier_counts = {}
    for col in imputed_df.select_dtypes(include='number'):
        q1 = imputed_df[col].quantile(0.25)
        q3 = imputed_df[col].quantile(0.75)
        iqr = q3 - q1
        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr
        outliers = imputed_df[(imputed_df[col] < lower_bound) | (imputed_df[col] > upper_bound)].shape[0]
        outlier_counts[col] = outliers

    outlier_counts = dict(sorted(outlier_counts.items(), key=lambda x: x[1], reverse=True))
    return outlier_counts

print("Mean skewness of dataset before outlier removal:", imputed_df.skew(numeric_only=True).mean())
detect_outliers(imputed_df)

Mean skewness of dataset before outlier removal: 4.275884397833871

{'c_time_lastob_start': 27351,
 't_actual_od_span': 26949,
 'c_rcs_estimate': 23611,
 'c_position_covariance_det': 23544,
 't_obs_available': 21243,
 't_obs_used': 20807,
 't_position_covariance_det': 20459,
 't_sedr': 20090,
 't_ctdot_r': 19262,
 'c_crdot_t': 19142,
 'max_risk_scaling': 17789,
 'elevation': 17495,
 't_recommended_od_span': 17086,
 't_sigma_t': 15381,
 'c_crdot_n': 15107,
 'c_cndot_t': 15096,
 'c_cndot_rdot': 14994,
 'c_ctdot_r': 14914,
 'relative_position_t': 14900,
 'c_obs_available': 14799,
 'c_cn_t': 14682,
 'c_obs_used': 14293,
 't_sigma_rdot': 14113,
 'c_sedr': 14086,
 'c_sigma_rdot': 13870,
 'c_sigma_t': 13717,
 't_crdot_t': 13118,
 'c_sigma_ndot': 13054,
 'relative_position_r': 12986,
 'c_sigma_r': 12797,
 't_ct_r': 12598,
 'c_sigma_tdot': 12570,
 'c_sigma_n': 12252,
 't_sigma_ndot': 12078,
 'F10': 11544,
 't_ctdot_t': 10982,
 'c_ctdot_rdot': 10867,
 'c_ctdot_t': 10781,
 'relative_position_n': 10637,
 'c_j2k_ecc': 10334,
 't_crdot_r': 10318,
 'relative_velocity_r': 10291,
 'mahalanobis_distance': 9843,
 'F3M': 9792,
 't_ctdot_rdot': 9509,
 'c_cr_area_over_mass': 9306,
 'AP': 9126,
 't_sigma_n': 8671,
 't_sigma_r': 8363,
 'c_cd_area_over_mass': 8338,
 'c_residuals_accepted': 7999,
 't_cndot_tdot': 7730,
 't_cn_t': 7659,
 't_cndot_r': 7642,
 't_crdot_n': 7639,
 't_residuals_accepted': 7498,
 't_sigma_tdot': 7456,
 'c_span': 7331,
 't_cndot_t': 7219,
 't_cndot_rdot': 7191,
 'c_h_apo': 6653,
 'SSN': 6187,
 't_h_apo': 6068,
 't_j2k_sma': 6063,
 't_cr_area_over_mass': 5637,
 'c_recommended_od_span': 4610,
 'c_j2k_sma': 4327,
 't_h_per': 4327,
 'c_weighted_rms': 3975,
 'c_actual_od_span': 3669,
 't_ctdot_n': 3309,
 't_cd_area_over_mass': 3200,
 't_cn_r': 3099,
 't_rcs_estimate': 2781,
 'c_j2k_inc': 1717,
 'c_h_per': 1506,
 'miss_distance': 986,
 't_j2k_ecc': 955,
 'max_risk_estimate': 811,
 'mission_id': 395,
 't_weighted_rms': 152,
 't_time_lastob_start': 75,
 't_time_lastob_end': 75,
 'event_id': 0,
 'time_to_tca': 0,
 'risk': 0,
 'relative_speed': 0,
 'relative_velocity_t': 0,
 'relative_velocity_n': 0,
 't_j2k_inc': 0,
 't_cndot_n': 0,
 'c_time_lastob_end': 0,
 'c_ct_r': 0,
 'c_cn_r': 0,
 'c_crdot_r': 0,
 'c_ctdot_n': 0,
 'c_cndot_r': 0,
 'c_cndot_n': 0,
 'c_cndot_tdot': 0,
 't_span': 0,
 'geocentric_latitude': 0,
 'azimuth': 0}

In [43]:
clean_df = imputed_df.copy()
for col in imputed_df.select_dtypes(include='number'):
        q1 = imputed_df[col].quantile(0.25)
        q3 = imputed_df[col].quantile(0.75)
        iqr = q3 - q1
        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr
        
        # Replace outliers with the lower and upper bounds
        clean_df.loc[imputed_df[col] < lower_bound, col] = lower_bound
        clean_df.loc[imputed_df[col] > upper_bound, col] = upper_bound

print("Mean skewness of outlier removed dataset: ",clean_df.skew(numeric_only=True).mean())
detect_outliers(clean_df)

C:\Users\Atharva\AppData\Local\Temp\ipykernel_6124\3076168684.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-6542.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  clean_df.loc[imputed_df[col] < lower_bound, col] = lower_bound

Mean skewness of outlier removed dataset:  0.37451790413488145

{'event_id': 0,
 'time_to_tca': 0,
 'mission_id': 0,
 'risk': 0,
 'max_risk_estimate': 0,
 'max_risk_scaling': 0,
 'miss_distance': 0,
 'relative_speed': 0,
 'relative_position_r': 0,
 'relative_position_t': 0,
 'relative_position_n': 0,
 'relative_velocity_r': 0,
 'relative_velocity_t': 0,
 'relative_velocity_n': 0,
 't_time_lastob_start': 0,
 't_time_lastob_end': 0,
 't_recommended_od_span': 0,
 't_actual_od_span': 0,
 't_obs_available': 0,
 't_obs_used': 0,
 't_residuals_accepted': 0,
 't_weighted_rms': 0,
 't_rcs_estimate': 0,
 't_cd_area_over_mass': 0,
 't_cr_area_over_mass': 0,
 't_sedr': 0,
 't_j2k_sma': 0,
 't_j2k_ecc': 0,
 't_j2k_inc': 0,
 't_ct_r': 0,
 't_cn_r': 0,
 't_cn_t': 0,
 't_crdot_r': 0,
 't_crdot_t': 0,
 't_crdot_n': 0,
 't_ctdot_r': 0,
 't_ctdot_t': 0,
 't_ctdot_n': 0,
 't_ctdot_rdot': 0,
 't_cndot_r': 0,
 't_cndot_t': 0,
 't_cndot_n': 0,
 't_cndot_rdot': 0,
 't_cndot_tdot': 0,
 'c_time_lastob_start': 0,
 'c_time_lastob_end': 0,
 'c_recommended_od_span': 0,
 'c_actual_od_span': 0,
 'c_obs_available': 0,
 'c_obs_used': 0,
 'c_residuals_accepted': 0,
 'c_weighted_rms': 0,
 'c_rcs_estimate': 0,
 'c_cd_area_over_mass': 0,
 'c_cr_area_over_mass': 0,
 'c_sedr': 0,
 'c_j2k_sma': 0,
 'c_j2k_ecc': 0,
 'c_j2k_inc': 0,
 'c_ct_r': 0,
 'c_cn_r': 0,
 'c_cn_t': 0,
 'c_crdot_r': 0,
 'c_crdot_t': 0,
 'c_crdot_n': 0,
 'c_ctdot_r': 0,
 'c_ctdot_t': 0,
 'c_ctdot_n': 0,
 'c_ctdot_rdot': 0,
 'c_cndot_r': 0,
 'c_cndot_t': 0,
 'c_cndot_n': 0,
 'c_cndot_rdot': 0,
 'c_cndot_tdot': 0,
 't_span': 0,
 'c_span': 0,
 't_h_apo': 0,
 't_h_per': 0,
 'c_h_apo': 0,
 'c_h_per': 0,
 'geocentric_latitude': 0,
 'azimuth': 0,
 'elevation': 0,
 'mahalanobis_distance': 0,
 't_position_covariance_det': 0,
 'c_position_covariance_det': 0,
 't_sigma_r': 0,
 'c_sigma_r': 0,
 't_sigma_t': 0,
 'c_sigma_t': 0,
 't_sigma_n': 0,
 'c_sigma_n': 0,
 't_sigma_rdot': 0,
 'c_sigma_rdot': 0,
 't_sigma_tdot': 0,
 'c_sigma_tdot': 0,
 't_sigma_ndot': 0,
 'c_sigma_ndot': 0,
 'F10': 0,
 'F3M': 0,
 'SSN': 0,
 'AP': 0}

The c_object_type is a categorical variable. The category value is replaced with the median value of risk for that particular category. 

This provides a numeric relation between the categorical variable and the target variable (i.e. risk)

In [44]:
#category c_object_type
print(clean_df['c_object_type'].value_counts())
risk_medians = clean_df.groupby(['c_object_type'])['risk'].median()
clean_df['c_object_type'] = clean_df['c_object_type'].map(risk_medians)

c_object_type
DEBRIS         65108
UNKNOWN        35235
PAYLOAD        10130
ROCKET BODY     1358
TBA              108
Name: count, dtype: int64

In [47]:
clean_df.to_csv('clean_data.csv', index=False)